using Company.Entity.Products;
using Company.WebAPI.Infrastructure.Mappers.Base;
using Company.WebAPI.ViewModels.ProductViewModels.BulatProductViewModels;

namespace Company.WebAPI.Infrastructure.Mappers.ProductMappers;

public class BulatProductMapperConfig : BaseMapperConfig
{
    public BulatProductMapperConfig()
    {
        #region CreateMap BulatProductViewModel

        CreateMap<BulatProduct, BulatProductViewModel>()
            .ForMember(x => x.Id, o => o.MapFrom(x => x.Id))
            .ForMember(x => x.PropertyParserId, o => o.MapFrom(x => x.PropertyParserId))
            .ForMember(x => x.URL, o => o.MapFrom(x => x.URL))
            .ForMember(x => x.Name, o => o.MapFrom(x => x.Name))
            .ForMember(x => x.Manufacturer, o => o.MapFrom(x => x.Manufacturer))
            .ForMember(x => x.Article, o => o.MapFrom(x => x.Article))
            .ForMember(x => x.Weight, o => o.MapFrom(x => x.Weight))
            .ForMember(x => x.Vendor, o => o.MapFrom(x => x.Vendor))
            .ForMember(x => x.CodeProduct, o => o.MapFrom(x => x.CodeProduct))
            .ForMember(x => x.Description, o => o.MapFrom(x => x.Description))
            .ForMember(x => x.Price, o => o.MapFrom(x => x.Price))
            .ForMember(x => x.Availability, o => o.MapFrom(x => x.Availability))
            .ForMember(x => x.AvailabilityType, o => o.MapFrom(x => x.AvailabilityType))
            .ForMember(x => x.Color, o => o.MapFrom(x => x.Color))
            .ForMember(x => x.Compatibility, o => o.MapFrom(x => x.Compatibility))
            .ForMember(x => x.LengthWidthHeight, o => o.MapFrom(x => x.LengthWidthHeight))
            .ForMember(x => x.Model, o => o.MapFrom(x => x.Model))
            .ForMember(x => x.AnalogProduct, o => o.MapFrom(x => x.AnalogProduct))
            .ForMember(x => x.Resource, o => o.MapFrom(x => x.Resource))
            .ForMember(x => x.TypeProduct, o => o.MapFrom(x => x.TypeProduct))
            .ForMember(x => x.TypeEquipment, o => o.MapFrom(x => x.TypeEquipment))
            .ForMember(x => x.OriginallyProduct, o => o.MapFrom(x => x.OriginallyProduct))
            .ForMember(x => x.SeriesProduct, o => o.MapFrom(x => x.SeriesProduct))
            .ForMember(x => x.PriceFrom5, o => o.MapFrom(x => x.PriceFrom5))
            .ForMember(x => x.PriceFrom10, o => o.MapFrom(x => x.PriceFrom10));

        CreateMap<BulatProductViewModel, BulatProduct>()
            .ForMember(x => x.Id, o => o.MapFrom(x => x.Id))
            .ForMember(x => x.PropertyParserId, o => o.MapFrom(x => x.PropertyParserId))
            .ForMember(x => x.URL, o => o.MapFrom(x => x.URL))
            .ForMember(x => x.Name, o => o.MapFrom(x => x.Name))
            .ForMember(x => x.Manufacturer, o => o.MapFrom(x => x.Manufacturer))
            .ForMember(x => x.Article, o => o.MapFrom(x => x.Article))
            .ForMember(x => x.Weight, o => o.MapFrom(x => x.Weight))
            .ForMember(x => x.Vendor, o => o.MapFrom(x => x.Vendor))
            .ForMember(x => x.CodeProduct, o => o.MapFrom(x => x.CodeProduct))
            .ForMember(x => x.Description, o => o.MapFrom(x => x.Description))
            .ForMember(x => x.Price, o => o.MapFrom(x => x.Price))
            .ForMember(x => x.Availability, o => o.MapFrom(x => x.Availability))
            .ForMember(x => x.AvailabilityType, o => o.MapFrom(x => x.AvailabilityType))
            .ForMember(x => x.Color, o => o.MapFrom(x => x.Color))
            .ForMember(x => x.Compatibility, o => o.MapFrom(x => x.Compatibility))
            .ForMember(x => x.LengthWidthHeight, o => o.MapFrom(x => x.LengthWidthHeight))
            .ForMember(x => x.Model, o => o.MapFrom(x => x.Model))
            .ForMember(x => x.AnalogProduct, o => o.MapFrom(x => x.AnalogProduct))
            .ForMember(x => x.Resource, o => o.MapFrom(x => x.Resource))
            .ForMember(x => x.TypeProduct, o => o.MapFrom(x => x.TypeProduct))
            .ForMember(x => x.TypeEquipment, o => o.MapFrom(x => x.TypeEquipment))
            .ForMember(x => x.OriginallyProduct, o => o.MapFrom(x => x.OriginallyProduct))
            .ForMember(x => x.SeriesProduct, o => o.MapFrom(x => x.SeriesProduct))
            .ForMember(x => x.PriceFrom5, o => o.MapFrom(x => x.PriceFrom5))
            .ForMember(x => x.PriceFrom10, o => o.MapFrom(x => x.PriceFrom10))
            .ForMember(x => x.CreatedAt, o => o.Ignore())
            .ForMember(x => x.CreatedBy, o => o.Ignore())
            .ForMember(x => x.UpdatedAt, o => o.Ignore())
            .ForMember(x => x.UpdatedBy, o => o.Ignore());

        #endregion

        #region CreateMap CreateBulatProductViewModel

        CreateMap<BulatProduct, CreateBulatProductViewModel>()
            .ForMember(x => x.PropertyParserId, o => o.MapFrom(x => x.PropertyParserId))
            .ForMember(x => x.URL, o => o.MapFrom(x => x.URL))
            .ForMember(x => x.Name, o => o.MapFrom(x => x.Name))
            .ForMember(x => x.Manufacturer, o => o.MapFrom(x => x.Manufacturer))
            .ForMember(x => x.Article, o => o.MapFrom(x => x.Article))
            .ForMember(x => x.Weight, o => o.MapFrom(x => x.Weight))
            .ForMember(x => x.Vendor, o => o.MapFrom(x => x.Vendor))
            .ForMember(x => x.CodeProduct, o => o.MapFrom(x => x.CodeProduct))
            .ForMember(x => x.Description, o => o.MapFrom(x => x.Description))
            .ForMember(x => x.Price, o => o.MapFrom(x => x.Price))
            .ForMember(x => x.Availability, o => o.MapFrom(x => x.Availability))
            .ForMember(x => x.AvailabilityType, o => o.MapFrom(x => x.AvailabilityType))
            .ForMember(x => x.Color, o => o.MapFrom(x => x.Color))
            .ForMember(x => x.Compatibility, o => o.MapFrom(x => x.Compatibility))
            .ForMember(x => x.LengthWidthHeight, o => o.MapFrom(x => x.LengthWidthHeight))
            .ForMember(x => x.Model, o => o.MapFrom(x => x.Model))
            .ForMember(x => x.AnalogProduct, o => o.MapFrom(x => x.AnalogProduct))
            .ForMember(x => x.Resource, o => o.MapFrom(x => x.Resource))
            .ForMember(x => x.TypeProduct, o => o.MapFrom(x => x.TypeProduct))
            .ForMember(x => x.TypeEquipment, o => o.MapFrom(x => x.TypeEquipment))
            .ForMember(x => x.OriginallyProduct, o => o.MapFrom(x => x.OriginallyProduct))
            .ForMember(x => x.SeriesProduct, o => o.MapFrom(x => x.SeriesProduct))
            .ForMember(x => x.PriceFrom5, o => o.MapFrom(x => x.PriceFrom5))
            .ForMember(x => x.PriceFrom10, o => o.MapFrom(x => x.PriceFrom10));

        CreateMap<CreateBulatProductViewModel, BulatProduct>()
            .ForMember(x => x.PropertyParserId, o => o.MapFrom(x => x.PropertyParserId))
            .ForMember(x => x.URL, o => o.MapFrom(x => x.URL))
            .ForMember(x => x.Name, o => o.MapFrom(x => x.Name))
            .ForMember(x => x.Manufacturer, o => o.MapFrom(x => x.Manufacturer))
            .ForMember(x => x.Article, o => o.MapFrom(x => x.Article))
            .ForMember(x => x.Weight, o => o.MapFrom(x => x.Weight))
            .ForMember(x => x.Vendor, o => o.MapFrom(x => x.Vendor))
            .ForMember(x => x.CodeProduct, o => o.MapFrom(x => x.CodeProduct))
            .ForMember(x => x.Description, o => o.MapFrom(x => x.Description))
            .ForMember(x => x.Price, o => o.MapFrom(x => x.Price))
            .ForMember(x => x.Availability, o => o.MapFrom(x => x.Availability))
            .ForMember(x => x.AvailabilityType, o => o.MapFrom(x => x.AvailabilityType))
            .ForMember(x => x.Color, o => o.MapFrom(x => x.Color))
            .ForMember(x => x.Compatibility, o => o.MapFrom(x => x.Compatibility))
            .ForMember(x => x.LengthWidthHeight, o => o.MapFrom(x => x.LengthWidthHeight))
            .ForMember(x => x.Model, o => o.MapFrom(x => x.Model))
            .ForMember(x => x.AnalogProduct, o => o.MapFrom(x => x.AnalogProduct))
            .ForMember(x => x.Resource, o => o.MapFrom(x => x.Resource))
            .ForMember(x => x.TypeProduct, o => o.MapFrom(x => x.TypeProduct))
            .ForMember(x => x.TypeEquipment, o => o.MapFrom(x => x.TypeEquipment))
            .ForMember(x => x.OriginallyProduct, o => o.MapFrom(x => x.OriginallyProduct))
            .ForMember(x => x.SeriesProduct, o => o.MapFrom(x => x.SeriesProduct))
            .ForMember(x => x.PriceFrom5, o => o.MapFrom(x => x.PriceFrom5))
            .ForMember(x => x.PriceFrom10, o => o.MapFrom(x => x.PriceFrom10))
            .ForMember(x => x.Id, o => o.Ignore())
            .ForMember(x => x.CreatedAt, o => o.Ignore())
            .ForMember(x => x.CreatedBy, o => o.Ignore())
            .ForMember(x => x.UpdatedAt, o => o.Ignore())
            .ForMember(x => x.UpdatedBy, o => o.Ignore());

        #endregion

        #region CreateMap UpdateBulatProductViewModel

        CreateMap<BulatProduct, UpdateBulatProductViewModel>()
            .ForMember(x => x.Id, o => o.MapFrom(x => x.Id))
            .ForMember(x => x.PropertyParserId, o => o.MapFrom(x => x.PropertyParserId))
            .ForMember(x => x.URL, o => o.MapFrom(x => x.URL))
            .ForMember(x => x.Name, o => o.MapFrom(x => x.Name))
            .ForMember(x => x.Manufacturer, o => o.MapFrom(x => x.Manufacturer))
            .ForMember(x => x.Article, o => o.MapFrom(x => x.Article))
            .ForMember(x => x.Weight, o => o.MapFrom(x => x.Weight))
            .ForMember(x => x.Vendor, o => o.MapFrom(x => x.Vendor))
            .ForMember(x => x.CodeProduct, o => o.MapFrom(x => x.CodeProduct))
            .ForMember(x => x.Description, o => o.MapFrom(x => x.Description))
            .ForMember(x => x.Price, o => o.MapFrom(x => x.Price))
            .ForMember(x => x.Availability, o => o.MapFrom(x => x.Availability))
            .ForMember(x => x.AvailabilityType, o => o.MapFrom(x => x.AvailabilityType))
            .ForMember(x => x.Color, o => o.MapFrom(x => x.Color))
            .ForMember(x => x.Compatibility, o => o.MapFrom(x => x.Compatibility))
            .ForMember(x => x.LengthWidthHeight, o => o.MapFrom(x => x.LengthWidthHeight))
            .ForMember(x => x.Model, o => o.MapFrom(x => x.Model))
            .ForMember(x => x.AnalogProduct, o => o.MapFrom(x => x.AnalogProduct))
            .ForMember(x => x.Resource, o => o.MapFrom(x => x.Resource))
            .ForMember(x => x.TypeProduct, o => o.MapFrom(x => x.TypeProduct))
            .ForMember(x => x.TypeEquipment, o => o.MapFrom(x => x.TypeEquipment))
            .ForMember(x => x.OriginallyProduct, o => o.MapFrom(x => x.OriginallyProduct))
            .ForMember(x => x.SeriesProduct, o => o.MapFrom(x => x.SeriesProduct))
            .ForMember(x => x.PriceFrom5, o => o.MapFrom(x => x.PriceFrom5))
            .ForMember(x => x.PriceFrom10, o => o.MapFrom(x => x.PriceFrom10));

        CreateMap<UpdateBulatProductViewModel, BulatProduct>()
            .ForMember(x => x.Id, o => o.MapFrom(x => x.Id))
            .ForMember(x => x.PropertyParserId, o => o.MapFrom(x => x.PropertyParserId))
            .ForMember(x => x.URL, o => o.MapFrom(x => x.URL))
            .ForMember(x => x.Name, o => o.MapFrom(x => x.Name))
            .ForMember(x => x.Manufacturer, o => o.MapFrom(x => x.Manufacturer))
            .ForMember(x => x.Article, o => o.MapFrom(x => x.Article))
            .ForMember(x => x.Weight, o => o.MapFrom(x => x.Weight))
            .ForMember(x => x.Vendor, o => o.MapFrom(x => x.Vendor))
            .ForMember(x => x.CodeProduct, o => o.MapFrom(x => x.CodeProduct))
            .ForMember(x => x.Description, o => o.MapFrom(x => x.Description))
            .ForMember(x => x.Price, o => o.MapFrom(x => x.Price))
            .ForMember(x => x.Availability, o => o.MapFrom(x => x.Availability))
            .ForMember(x => x.AvailabilityType, o => o.MapFrom(x => x.AvailabilityType))
            .ForMember(x => x.Color, o => o.MapFrom(x => x.Color))
            .ForMember(x => x.Compatibility, o => o.MapFrom(x => x.Compatibility))
            .ForMember(x => x.LengthWidthHeight, o => o.MapFrom(x => x.LengthWidthHeight))
            .ForMember(x => x.Model, o => o.MapFrom(x => x.Model))
            .ForMember(x => x.AnalogProduct, o => o.MapFrom(x => x.AnalogProduct))
            .ForMember(x => x.Resource, o => o.MapFrom(x => x.Resource))
            .ForMember(x => x.TypeProduct, o => o.MapFrom(x => x.TypeProduct))
            .ForMember(x => x.TypeEquipment, o => o.MapFrom(x => x.TypeEquipment))
            .ForMember(x => x.OriginallyProduct, o => o.MapFrom(x => x.OriginallyProduct))
            .ForMember(x => x.SeriesProduct, o => o.MapFrom(x => x.SeriesProduct))
            .ForMember(x => x.PriceFrom5, o => o.MapFrom(x => x.PriceFrom5))
            .ForMember(x => x.PriceFrom10, o => o.MapFrom(x => x.PriceFrom10))
            .ForMember(x => x.CreatedAt, o => o.Ignore())
            .ForMember(x => x.CreatedBy, o => o.Ignore())
            .ForMember(x => x.UpdatedAt, o => o.Ignore())
            .ForMember(x => x.UpdatedBy, o => o.Ignore());

        #endregion
    }
}